### ISSUE TITLE
ClassSelector is written into generated class

### ISSUE THREAD

**Issue by shardt68** [stefanocke/japkit#13]
the Line in VO Template 
@ClassSelector(kind = ClassSelectorKind.TEMPLATE)
    TransformSingleValueType<SrcTypeToGenerated> mapPropertyType;
generates:
	ExampleVO mapPropertyType;
in  
ExampleVO

is it a bug or should it be placed someware else?

[japkit-starter.zip](https://github.com/stefanocke/japkit/files/902685/japkit-starter.zip)

**Comment by shardt68** [comment]
nebenbei warum geht es obwohl die konfiguration falsch ist?
<compilerArg>-Aannotations=de.mms_dresden.dosv.templates.*</compilerArg>

**Comment by stefanocke** [comment]
The only place where fields are recognized as functions is within Switch classes.
So, the code mentioned above represents a field rule.

**Comment by stefanocke** [comment]
See answer above. In general, some documentation on declaration and usage of functions is needed.
